// Learn each joint's range of motion from the game's own animation clips (UAL + CMU mocap + the
// authored ones), the way pose-conditioned joint limits are learned from mocap: for every limited
// bone, over every frame of every clip, take the rotation from rest, find the hinge it mostly turns
// about, and record the flexion range and how far it strays from the hinge (the "cone").
// Writes src/courier/anim/romdata.js (bone -> { hinge, min, max, cone }), which rom.js uses for the Courier's fingers and
// thumbs: it supplies each joint's true hinge (the rig's finger bones are not consistent, and the left and
// right sides are mirrored), and the range is then held inside a human envelope (RIGIFY in rom.js). Elbows,
// knees and wrists are not one-axis joints in mocap, so those keep hand-set limits.
//
//   npm run dev &      (or URL=http://host:port/)
//   node scripts/learn_rom.mjs
import { chromium } from 'playwright';
import fs from 'fs';

const url = process.env.URL || 'http://127.0.0.1:5173/';
const exe = process.env.CHROMIUM || '/opt/pw-browsers/chromium-1194/chrome-linux/chrome';
const browser = await chromium.launch({ executablePath: fs.existsSync(exe) ? exe : undefined, args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const page = await browser.newPage({ viewport: { width: 480, height: 300 } });
await page.addInitScript(() => { Object.defineProperty(window, '__game', { configurable: true, set(v) { v.manual = true; this.__g = v; }, get() { return this.__g; } }); });
await page.goto(url, { waitUntil: 'commit' });
for (let i = 0; i < 90; i++) { await new Promise((r) => setTimeout(r, 1000)); if (await page.evaluate('!!window.__ready').catch(() => false)) break; }
const out = await page.evaluate(() => {
  const g = __game, ch = g.character, C = ch.clips, THREE = g.THREE;
  const table = {};
  const names = Object.keys(ch.bones).filter((n) => /^(f_(index|middle|ring|pinky)0[123]|thumb0[123])[LR]$/.test(n));
  for (const n of names) {
    const i = C.index[n]; if (i === undefined) continue;
    const rest = ch.rest.get(ch.bones[n]).q;
    const ri = rest.clone().invert();
    const ds = [];
    const axSum = new THREE.Vector3();
    for (const clip of Object.values(C.clips)) {
      for (let f = 0; f < clip.n; f++) {
        const o = (f * C.nb + i) * 4;
        const d = ri.clone().multiply(new THREE.Quaternion(clip.q[o], clip.q[o + 1], clip.q[o + 2], clip.q[o + 3]));
        if (d.w < 0) { d.x = -d.x; d.y = -d.y; d.z = -d.z; d.w = -d.w; }
        const ang = 2 * Math.atan2(Math.hypot(d.x, d.y, d.z), d.w);
        if (ang > 0.02) axSum.addScaledVector(new THREE.Vector3(d.x, d.y, d.z).normalize(), ang * ang); // (big bends count for more)
        ds.push(d);
      }
    }
    if (axSum.lengthSq() < 1e-9) continue;
    const h = axSum.normalize();
    const flex = [], swing = [];
    for (const d of ds) {
      const p = d.x * h.x + d.y * h.y + d.z * h.z;
      const t = new THREE.Quaternion(h.x * p, h.y * p, h.z * p, d.w).normalize();
      flex.push(2 * Math.atan2(t.x * h.x + t.y * h.y + t.z * h.z, t.w));
      const s = d.clone().multiply(t.clone().invert());
      swing.push(2 * Math.atan2(Math.hypot(s.x, s.y, s.z), Math.abs(s.w)));
    }
    const pct = (a, q) => { const b = [...a].sort((x, y) => x - y); return b[Math.min(b.length - 1, Math.max(0, Math.round(q * (b.length - 1))))]; };
    table[n] = { hinge: h.toArray().map((v) => +v.toFixed(3)), min: +pct(flex, 0.002).toFixed(2), max: +pct(flex, 0.998).toFixed(2), cone: +pct(swing, 0.998).toFixed(2), frames: ds.length };
  }
  return table;
});
await browser.close();
const M = 0.15; // margin, radians, on every side
const rows = Object.entries(out).map(([n, t]) => `  ${n}: { hinge: [${t.hinge.join(', ')}], min: ${+(t.min - M).toFixed(2)}, max: ${+(t.max + M).toFixed(2)}, cone: ${+(t.cone + M).toFixed(2)} },`);
fs.writeFileSync(new URL('../src/romdata.js', import.meta.url), `// Generated by scripts/learn_rom.mjs from the game's own clips (${Object.values(out)[0]?.frames} frames each): do not edit by hand.\n// bone -> { hinge (local axis, flexion is positive about it), min, max (radians), cone (radians) }\nexport const LEARNED = {\n${rows.join('\n')}\n};\n`);
console.log(rows.join('\n'));
